# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      # Overrides the fallback 127.0.0.1 string in your index.js to point to the mongo container
      - MONGO_URI=mongodb://mongodb:27017/ecoders_jira
      - PORT=5000
    depends_on:
      - mongodb
    volumes:
      - backend_uploads:/usr/src/app/uploads

  frontend:
    build: ./client
    ports:
      - "5173:80" # Maps localhost:5173 to the Nginx port 80
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  backend_uploads: